# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Sidedish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 5.1'
    pod 'Toaster'

  # Pods for Sidedish

  target 'SidedishTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
