# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Sidedish' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!
    pod 'Alamofire', '~> 5.1'
    # pod 'Toaster'
    pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'

  target 'SidedishTests' do
    inherit! :search_paths
  end

end
